version: '3.1'

services:
  banco-dados:
    image: postgres
    container_name: admin-pedidos-banco-dados
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - C:\dev\postgre-sql\Docker\admin-pedidos\data:/var/lib/postgresql/data 

