import { AmbientesAplicacao } from "./ambientes-aplicacao.app";

export const ConfiguracoesGlobaisApp = {
    CURRENT_ENVIRONMENT: process.env.CURRENT_ENVIRONMENT || AmbientesAplicacao.DESENVOLVIMENTO_LOCAL,
    APIS_SALT_KEY: process.env.APIS_SALT_KEY || '',

    CONTA_ARMAZENAMENTO_ARQUIVOS_CONFIGURACOES_ACESSO: process.env.CONTA_ARMAZENAMENTO_ARQUIVOS_CONFIGURACOES_ACESSO || '',
    CONTA_ARMAZENAMENTO_ARQUIVOS_URL_IMAGENS_PRODUTO: process.env.CONTA_ARMAZENAMENTO_ARQUIVOS_URL_IMAGENS_PRODUTO || '',
    URL_ARMAZENAMENTO_IMAGENS_PRODUTOS: (process.env.CONTA_ARMAZENAMENTO_ARQUIVOS_URL_ACESSO || '') + '/' + (process.env.CONTA_ARMAZENAMENTO_ARQUIVOS_URL_IMAGENS_PRODUTO + '')
}