import { Environments } from "./environments";

export const GlobalSettings = {
    CURRENT_ENVIRONMENT: process.env.CURRENT_ENVIRONMENT || Environments.DESENVOLVIMENTO_LOCAL,
    APIS_SALT_KEY: process.env.APIS_SALT_KEY || '',

    FILES_STORAGE_ACCOUNT__ACCESS_SETTINGS: process.env.FILES_STORAGE_ACCOUNT__ACCESS_SETTINGS || '',
    FILES_STORAGE_ACCOUNT__URL_PRODUCT_IMAGES: process.env.FILES_STORAGE_ACCOUNT__URL_PRODUCT_IMAGES || '',
    URL_ARMAZENAMENTO_IMAGENS_PRODUTOS: (process.env.FILES_STORAGE_ACCOUNT__ACCESS_URL || '') + '/' + (process.env.FILES_STORAGE_ACCOUNT__URL_PRODUCT_IMAGES + '')
}
